--- SQL Test Cases for compare_load_md5_metadata_tbl function

-- Report after Second Load:
-- Expected Changes:
-- 1. RENAMED: location to location_old
-- 2. DELETED: ternary_location
-- 3. ADDED: location_new

test_db=# SELECT * FROM pdcd_schema.compare_load_md5_metadata_tbl(ARRAY['analytics_schema']);
 metadata_id | snapshot_id |   schema_name    | object_type | object_type_name | object_subtype | object_subtype_name |                                                                                        object_subtype_details                                                                                         |            object_md5            |       processed_time       | change_type
-------------+-------------+------------------+-------------+------------------+----------------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------+-------------
           7 |           2 | analytics_schema | Table       | departments      | Column         | location_new        | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:7                 | 194c7795dfa2987255dfc248e379b863 | 2025-11-07 17:36:04.282162 | ADDED
           8 |           2 | analytics_schema | Table       | departments      | Column         | location_old        |                                                                                                                                                                                                       | d6e08099dee6077445cfbdf123772ea9 | 2025-11-07 17:36:04.282166 | RENAMED
           9 |           2 | analytics_schema | Table       | departments      | Column         | ternary_location    | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:6 | 61b2e3cf4714175ccdf73ef3e1838d22 | 2025-11-07 17:36:04.282167 | DELETED
(3 rows)

test_db=# select * from pdcd_schema.md5_metadata_tbl;
 metadata_id | snapshot_id |   schema_name    | object_type | object_type_name | object_subtype | object_subtype_name |                                                                                                                            object_subtype_details                                                                                                                             |            object_md5            |       processed_time       | change_type
-------------+-------------+------------------+-------------+------------------+----------------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------+-------------
           1 |           1 | analytics_schema | Table       | departments      | Column         | department_id       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1 | 57cdd3e718f6f0349c77a716434d09f8 | 2025-11-07 17:34:15.762256 | ADDED
           2 |           1 | analytics_schema | Table       | departments      | Column         | department_name     | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_department_name_key,ordinal_position:2                                           | f39e54388d58fa7378803e136d7de611 | 2025-11-07 17:34:15.76567  | ADDED
           3 |           1 | analytics_schema | Table       | departments      | Column         | location            | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3                                                                         | d6e08099dee6077445cfbdf123772ea9 | 2025-11-07 17:34:15.765694 | ADDED
           4 |           1 | analytics_schema | Table       | departments      | Column         | primary_location    | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4                                                                         | a4e83f1f87ade648d39ec2e7fbdce011 | 2025-11-07 17:34:15.7657   | ADDED
           5 |           1 | analytics_schema | Table       | departments      | Column         | secondary_location  | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:5                                                                         | 57ee8681eea9926a037ef391dc976a13 | 2025-11-07 17:34:15.765706 | ADDED
           6 |           1 | analytics_schema | Table       | departments      | Column         | ternary_location    | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:6                                                                         | 61b2e3cf4714175ccdf73ef3e1838d22 | 2025-11-07 17:34:15.765711 | ADDED
           7 |           2 | analytics_schema | Table       | departments      | Column         | location_new        | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:7                                                                                         | 194c7795dfa2987255dfc248e379b863 | 2025-11-07 17:36:04.28202  | ADDED
           8 |           2 | analytics_schema | Table       | departments      | Column         | location_old        |                                                                                                                                                                                                                                                                               | d6e08099dee6077445cfbdf123772ea9 | 2025-11-07 17:36:04.282087 | RENAMED
           9 |           2 | analytics_schema | Table       | departments      | Column         | ternary_location    | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:6                                                                         | 61b2e3cf4714175ccdf73ef3e1838d22 | 2025-11-07 17:36:04.282152 | DELETED
(9 rows)

-- Report after third Load:
-- Expected Changes:
-- 1. RENAMED: location_new to ternary_location
-- 2. DELETED: location_old
-- 3. ADDED: manager_id
-- 4. MODIFIED: department_name (length changed from 100 to 150)
test_db=# select * from pdcd_schema.compare_load_md5_metadata_tbl(ARRAY['analytics_schema']);
 metadata_id | snapshot_id |   schema_name    | object_type | object_type_name | object_subtype | object_subtype_name |                                                                                                       object_subtype_details                                                                                                        |            object_md5            |       processed_time       | change_type
-------------+-------------+------------------+-------------+------------------+----------------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------+-------------
          22 |           3 | analytics_schema | Table       | departments      | Column         | department_name     | data_type:character varying,max_length:150,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_department_name_key,ordinal_position:2 | f1e326b4a40aaa809aebffb844408a30 | 2025-11-07 18:37:52.088256 | MODIFIED
          24 |           3 | analytics_schema | Table       | departments      | Column         | location_old        | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3                               | d6e08099dee6077445cfbdf123772ea9 | 2025-11-07 18:37:52.08826  | DELETED
          23 |           3 | analytics_schema | Table       | departments      | Column         | manager_id          | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:8                                               | 310ec655a81af3aab542966c2f729edb | 2025-11-07 18:37:52.088261 | ADDED
          21 |           3 | analytics_schema | Table       | departments      | Column         | ternary_location    | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:7                                               | 194c7795dfa2987255dfc248e379b863 | 2025-11-07 18:37:52.088266 | RENAMED
(4 rows)

test_db=# select * from pdcd_schema.md5_metadata_tbl;
 metadata_id | snapshot_id |   schema_name    | object_type | object_type_name | object_subtype | object_subtype_name |                                                                                                                            object_subtype_details                                                                                                                             |            object_md5            |       processed_time       | change_type
-------------+-------------+------------------+-------------+------------------+----------------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------+-------------
           1 |           1 | analytics_schema | Table       | departments      | Column         | department_id       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1 | 57cdd3e718f6f0349c77a716434d09f8 | 2025-11-07 17:34:15.762256 | ADDED
           2 |           1 | analytics_schema | Table       | departments      | Column         | department_name     | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_department_name_key,ordinal_position:2                                           | f39e54388d58fa7378803e136d7de611 | 2025-11-07 17:34:15.76567  | ADDED
           3 |           1 | analytics_schema | Table       | departments      | Column         | location            | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3                                                                         | d6e08099dee6077445cfbdf123772ea9 | 2025-11-07 17:34:15.765694 | ADDED
           4 |           1 | analytics_schema | Table       | departments      | Column         | primary_location    | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4                                                                         | a4e83f1f87ade648d39ec2e7fbdce011 | 2025-11-07 17:34:15.7657   | ADDED
           5 |           1 | analytics_schema | Table       | departments      | Column         | secondary_location  | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:5                                                                         | 57ee8681eea9926a037ef391dc976a13 | 2025-11-07 17:34:15.765706 | ADDED
           6 |           1 | analytics_schema | Table       | departments      | Column         | ternary_location    | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:6                                                                         | 61b2e3cf4714175ccdf73ef3e1838d22 | 2025-11-07 17:34:15.765711 | ADDED
           7 |           2 | analytics_schema | Table       | departments      | Column         | location_new        | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:7                                                                                         | 194c7795dfa2987255dfc248e379b863 | 2025-11-07 17:36:04.28202  | ADDED
           8 |           2 | analytics_schema | Table       | departments      | Column         | location_old        |                                                                                                                                                                                                                                                                               | d6e08099dee6077445cfbdf123772ea9 | 2025-11-07 17:36:04.282087 | RENAMED
           9 |           2 | analytics_schema | Table       | departments      | Column         | ternary_location    | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:6                                                                         | 61b2e3cf4714175ccdf73ef3e1838d22 | 2025-11-07 17:36:04.282152 | DELETED
          21 |           3 | analytics_schema | Table       | departments      | Column         | ternary_location    | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:7                                                                                         | 194c7795dfa2987255dfc248e379b863 | 2025-11-07 18:37:52.083471 | RENAMED
          22 |           3 | analytics_schema | Table       | departments      | Column         | department_name     | data_type:character varying,max_length:150,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_department_name_key,ordinal_position:2                                           | f1e326b4a40aaa809aebffb844408a30 | 2025-11-07 18:37:52.086647 | MODIFIED
          23 |           3 | analytics_schema | Table       | departments      | Column         | manager_id          | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:8                                                                                         | 310ec655a81af3aab542966c2f729edb | 2025-11-07 18:37:52.086736 | ADDED
          24 |           3 | analytics_schema | Table       | departments      | Column         | location_old        | data_type:character varying,max_length:100,numeric_precision:,numeric_scale:,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3                                                                         | d6e08099dee6077445cfbdf123772ea9 | 2025-11-07 18:37:52.086809 | DELETED
(13 rows)