--- =============================
--- ========= TEST CASES ========
--- =============================

TRUNCATE TABLE pdcd_schema.md5_metadata_staging_tbl RESTART IDENTITY CASCADE;
TRUNCATE TABLE pdcd_schema.md5_metadata_tbl RESTART IDENTITY CASCADE;
TRUNCATE TABLE pdcd_schema.snapshot_tbl RESTART IDENTITY CASCADE;

DROP schema IF EXISTS analytics_schema CASCADE;
CREATE SCHEMA analytics_schema;

CREATE TABLE analytics_schema.employees (
    employee_id SERIAL PRIMARY KEY,
    employee_name TEXT NOT NULL,
    department_id INT,
    manager_id INT
);
CREATE TABLE analytics_schema.departments(
    department_id SERIAL PRIMARY KEY,
    department_name TEXT NOT NULL
);
CREATE TABLE analytics_schema.projects (
    project_id SERIAL PRIMARY KEY,
    project_name TEXT NOT NULL,
    owner_employee_id INT
);
CREATE TABLE analytics_schema.locations (
    location_id SERIAL PRIMARY KEY,
    location_name TEXT NOT NULL
);
-- =============================================================
-- First Run
-- =============================================================
    SELECT * FROM pdcd_schema.load_snapshot_tbl();
    SELECT * FROM pdcd_schema.load_md5_metadata_tbl(ARRAY['analytics_schema']);
    SELECT * FROM pdcd_schema.load_md5_metadata_staging_tbl(ARRAY['analytics_schema']);
SELECT snapshot_id,object_type_name, object_subtype,  object_subtype_name, object_md5,    change_type, object_subtype_details, processed_time
FROM pdcd_schema.md5_metadata_tbl;
 snapshot_id | object_type_name | object_subtype | object_subtype_name |            object_md5            | change_type |                                                                                                                            object_subtype_details                                                                                                                             |       processed_time
-------------+------------------+----------------+---------------------+----------------------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------
           1 | departments      | Column         | department_id       | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1 | 2025-11-18 18:58:04.919497
           1 | departments      | Column         | department_name     | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2                                                                                          | 2025-11-18 18:58:04.925646
           1 | employees        | Column         | employee_id         | 6b1b0723fc761b4f80b3ebd7347a2adc | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.employees_employee_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:employees_pkey,ordinal_position:1       | 2025-11-18 18:58:04.925669
           1 | employees        | Column         | employee_name       | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2                                                                                          | 2025-11-18 18:58:04.925675
           1 | employees        | Column         | department_id       | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3                                                                                   | 2025-11-18 18:58:04.925681
           1 | employees        | Column         | manager_id          | 23d773c000aa706b00d05e17a2b453dd | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4                                                                                   | 2025-11-18 18:58:04.925686
           1 | locations        | Column         | location_id         | 7e303cc5a87a43fd7d157c8d405ead5b | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.locations_location_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:locations_pkey,ordinal_position:1       | 2025-11-18 18:58:04.925691
           1 | locations        | Column         | location_name       | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2                                                                                          | 2025-11-18 18:58:04.925696
           1 | projects         | Column         | project_id          | dd4a969c61f7438005de9cb441488853 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.projects_project_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:projects_pkey,ordinal_position:1          | 2025-11-18 18:58:04.925702
           1 | projects         | Column         | project_name        | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2                                                                                          | 2025-11-18 18:58:04.925707
           1 | projects         | Column         | owner_employee_id   | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3                                                                                   | 2025-11-18 18:58:04.925713
           1 | departments      | Constraint     | departments_pkey    | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)                                                                                                                                                                                  | 2025-11-18 18:58:04.929295
           1 | employees        | Constraint     | employees_pkey      | 46e4d7c138cb7c7937bfd192b807b708 | ADDED       | constraint_type:PRIMARY KEY,column_name:employee_id,definition:PRIMARY KEY (employee_id)                                                                                                                                                                                      | 2025-11-18 18:58:04.929321
           1 | locations        | Constraint     | locations_pkey      | fb2872ae6f850928fc245309c234f463 | ADDED       | constraint_type:PRIMARY KEY,column_name:location_id,definition:PRIMARY KEY (location_id)                                                                                                                                                                                      | 2025-11-18 18:58:04.929328
           1 | projects         | Constraint     | projects_pkey       | 6f0219581bbe02a3a37894ac16b99524 | ADDED       | constraint_type:PRIMARY KEY,column_name:project_id,definition:PRIMARY KEY (project_id)                                                                                                                                                                                        | 2025-11-18 18:58:04.929333
           1 | departments      | Index          | departments_pkey    | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree                                                         | 2025-11-18 18:58:04.932945
           1 | employees        | Index          | employees_pkey      | 2ead719c29bb313dcd2fb7888d34134b | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX employees_pkey ON analytics_schema.employees USING btree (employee_id),is_unique:true,is_primary:true,index_columns:employee_id,index_predicate:,access_method:btree                                                                 | 2025-11-18 18:58:04.932965
           1 | locations        | Index          | locations_pkey      | c415021e5aaf76a347055504ddd89d2e | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX locations_pkey ON analytics_schema.locations USING btree (location_id),is_unique:true,is_primary:true,index_columns:location_id,index_predicate:,access_method:btree                                                                 | 2025-11-18 18:58:04.932979
           1 | projects         | Index          | projects_pkey       | dbf8303392b4b104fc49c2f1c98667e5 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX projects_pkey ON analytics_schema.projects USING btree (project_id),is_unique:true,is_primary:true,index_columns:project_id,index_predicate:,access_method:btree                                                                     | 2025-11-18 18:58:04.932984
(19 rows)
-- =============================================================
-- Test Run 1 — Initial FK Additions
-- =============================================================

-- Purpose: Basic foreign-key creation
ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_dept FOREIGN KEY (department_id)
    REFERENCES analytics_schema.departments(department_id);
ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_manager FOREIGN KEY (manager_id)
    REFERENCES analytics_schema.employees(employee_id);
ALTER TABLE analytics_schema.projects
    ADD CONSTRAINT fk_proj_owner FOREIGN KEY (owner_employee_id)
    REFERENCES analytics_schema.employees(employee_id);

    SELECT * FROM pdcd_schema.load_snapshot_tbl();
    SELECT * FROM pdcd_schema.compare_load_md5_metadata_tbl(ARRAY['analytics_schema']);
    TRUNCATE TABLE pdcd_schema.md5_metadata_staging_tbl RESTART IDENTITY CASCADE;
    SELECT * FROM pdcd_schema.load_md5_metadata_staging_tbl(ARRAY['analytics_schema']);

SELECT snapshot_id,object_type_name, object_subtype,    object_subtype_name, object_md5,    change_type, object_subtype_details from pdcd_schema.md5_metadata_tbl;
 snapshot_id | object_type_name | object_subtype | object_subtype_name |            object_md5            | change_type |                                                                                                                            object_subtype_details
-------------+------------------+----------------+---------------------+----------------------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
           1 | departments      | Column         | department_id       | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           1 | departments      | Column         | department_name     | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | employee_id         | 6b1b0723fc761b4f80b3ebd7347a2adc | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.employees_employee_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:employees_pkey,ordinal_position:1
           1 | employees        | Column         | employee_name       | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | department_id       | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | employees        | Column         | manager_id          | 23d773c000aa706b00d05e17a2b453dd | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4
           1 | locations        | Column         | location_id         | 7e303cc5a87a43fd7d157c8d405ead5b | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.locations_location_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:locations_pkey,ordinal_position:1
           1 | locations        | Column         | location_name       | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | project_id          | dd4a969c61f7438005de9cb441488853 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.projects_project_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:projects_pkey,ordinal_position:1
           1 | projects         | Column         | project_name        | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | owner_employee_id   | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | departments      | Constraint     | departments_pkey    | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           1 | employees        | Constraint     | employees_pkey      | 46e4d7c138cb7c7937bfd192b807b708 | ADDED       | constraint_type:PRIMARY KEY,column_name:employee_id,definition:PRIMARY KEY (employee_id)
           1 | locations        | Constraint     | locations_pkey      | fb2872ae6f850928fc245309c234f463 | ADDED       | constraint_type:PRIMARY KEY,column_name:location_id,definition:PRIMARY KEY (location_id)
           1 | projects         | Constraint     | projects_pkey       | 6f0219581bbe02a3a37894ac16b99524 | ADDED       | constraint_type:PRIMARY KEY,column_name:project_id,definition:PRIMARY KEY (project_id)
           1 | departments      | Index          | departments_pkey    | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           1 | employees        | Index          | employees_pkey      | 2ead719c29bb313dcd2fb7888d34134b | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX employees_pkey ON analytics_schema.employees USING btree (employee_id),is_unique:true,is_primary:true,index_columns:employee_id,index_predicate:,access_method:btree
           1 | locations        | Index          | locations_pkey      | c415021e5aaf76a347055504ddd89d2e | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX locations_pkey ON analytics_schema.locations USING btree (location_id),is_unique:true,is_primary:true,index_columns:location_id,index_predicate:,access_method:btree
           1 | projects         | Index          | projects_pkey       | dbf8303392b4b104fc49c2f1c98667e5 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX projects_pkey ON analytics_schema.projects USING btree (project_id),is_unique:true,is_primary:true,index_columns:project_id,index_predicate:,access_method:btree
           2 | employees        | Column         | department_id       | 8c589519c4e1bcb99712c94a36eab2a5 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           2 | employees        | Column         | manager_id          | 44274eded9170b1215e53e763c8ef725 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           2 | projects         | Column         | owner_employee_id   | 1e089843e40e8b5ad28d1193d17c7dca | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_proj_owner,ordinal_position:3
           2 | employees        | Constraint     | fk_emp_dept         | d15c5860c9bccaa7101d3622732d6aa7 | ADDED       | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           2 | employees        | Constraint     | fk_emp_manager      | 47616b219bed8eedf4c5d317305a56a6 | ADDED       | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           2 | projects         | Constraint     | fk_proj_owner       | 027aa00ae7569fb2d36ea6893728dc2d | ADDED       | constraint_type:FOREIGN KEY,column_name:owner_employee_id,definition:FOREIGN KEY (owner_employee_id) REFERENCES analytics_schema.employees(employee_id)
           2 | employees        | Reference      | fk_emp_dept         | b8d9ae77771da31847284c0e7d6d4462 | ADDED       | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
           2 | employees        | Reference      | fk_emp_manager      | 1d11e76a49d32520e6a69503c89d78c4 | ADDED       | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           2 | projects         | Reference      | fk_proj_owner       | e80df3f3baa79176a0352ea68ffc3db8 | ADDED       | source_column:owner_employee_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_proj_owner
(28 rows)

-- =============================================================
-- Test Run 2 — Renaming Columns & Updating FKs
-- =============================================================
-- Purpose: detect FK breakage + new mappings after renames
ALTER TABLE analytics_schema.employees
    RENAME COLUMN department_id TO dept_id;
ALTER TABLE analytics_schema.employees
    RENAME COLUMN manager_id TO supervisor_id;
-- Drop old FKs after renames
ALTER TABLE analytics_schema.employees DROP CONSTRAINT fk_emp_dept;
ALTER TABLE analytics_schema.employees DROP CONSTRAINT fk_emp_manager;

-- Recreate FKs using new column names
ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_dept_v2
    FOREIGN KEY (dept_id)
    REFERENCES analytics_schema.departments(department_id);
ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_supervisor_v2
    FOREIGN KEY (supervisor_id)
    REFERENCES analytics_schema.employees(employee_id);


    SELECT * FROM pdcd_schema.load_snapshot_tbl();
    SELECT * FROM pdcd_schema.compare_load_md5_metadata_tbl(ARRAY['analytics_schema']);
    TRUNCATE TABLE pdcd_schema.md5_metadata_staging_tbl RESTART IDENTITY CASCADE;
    SELECT * FROM pdcd_schema.load_md5_metadata_staging_tbl(ARRAY['analytics_schema']);
SELECT snapshot_id,object_type_name, object_subtype,    object_subtype_name, object_md5,    change_type, object_subtype_details from pdcd_schema.md5_metadata_tbl;
test_db=# SELECT snapshot_id,object_type_name, object_subtype,    object_subtype_name, object_md5,    change_type, object_subtype_details from pdcd_schema.md5_metadata_tbl;
 snapshot_id | object_type_name | object_subtype | object_subtype_name  |            object_md5            | change_type |                                                                                                                            object_subtype_details
-------------+------------------+----------------+----------------------+----------------------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
           1 | departments      | Column         | department_id        | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           1 | departments      | Column         | department_name      | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | employee_id          | 6b1b0723fc761b4f80b3ebd7347a2adc | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.employees_employee_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:employees_pkey,ordinal_position:1
           1 | employees        | Column         | employee_name        | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | department_id        | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | employees        | Column         | manager_id           | 23d773c000aa706b00d05e17a2b453dd | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4
           1 | locations        | Column         | location_id          | 7e303cc5a87a43fd7d157c8d405ead5b | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.locations_location_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:locations_pkey,ordinal_position:1
           1 | locations        | Column         | location_name        | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | project_id           | dd4a969c61f7438005de9cb441488853 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.projects_project_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:projects_pkey,ordinal_position:1
           1 | projects         | Column         | project_name         | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | owner_employee_id    | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | departments      | Constraint     | departments_pkey     | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           1 | employees        | Constraint     | employees_pkey       | 46e4d7c138cb7c7937bfd192b807b708 | ADDED       | constraint_type:PRIMARY KEY,column_name:employee_id,definition:PRIMARY KEY (employee_id)
           1 | locations        | Constraint     | locations_pkey       | fb2872ae6f850928fc245309c234f463 | ADDED       | constraint_type:PRIMARY KEY,column_name:location_id,definition:PRIMARY KEY (location_id)
           1 | projects         | Constraint     | projects_pkey        | 6f0219581bbe02a3a37894ac16b99524 | ADDED       | constraint_type:PRIMARY KEY,column_name:project_id,definition:PRIMARY KEY (project_id)
           1 | departments      | Index          | departments_pkey     | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           1 | employees        | Index          | employees_pkey       | 2ead719c29bb313dcd2fb7888d34134b | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX employees_pkey ON analytics_schema.employees USING btree (employee_id),is_unique:true,is_primary:true,index_columns:employee_id,index_predicate:,access_method:btree
           1 | locations        | Index          | locations_pkey       | c415021e5aaf76a347055504ddd89d2e | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX locations_pkey ON analytics_schema.locations USING btree (location_id),is_unique:true,is_primary:true,index_columns:location_id,index_predicate:,access_method:btree
           1 | projects         | Index          | projects_pkey        | dbf8303392b4b104fc49c2f1c98667e5 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX projects_pkey ON analytics_schema.projects USING btree (project_id),is_unique:true,is_primary:true,index_columns:project_id,index_predicate:,access_method:btree
           2 | employees        | Column         | department_id        | 8c589519c4e1bcb99712c94a36eab2a5 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           2 | employees        | Column         | manager_id           | 44274eded9170b1215e53e763c8ef725 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           2 | projects         | Column         | owner_employee_id    | 1e089843e40e8b5ad28d1193d17c7dca | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_proj_owner,ordinal_position:3
           2 | employees        | Constraint     | fk_emp_dept          | d15c5860c9bccaa7101d3622732d6aa7 | ADDED       | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           2 | employees        | Constraint     | fk_emp_manager       | 47616b219bed8eedf4c5d317305a56a6 | ADDED       | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           2 | projects         | Constraint     | fk_proj_owner        | 027aa00ae7569fb2d36ea6893728dc2d | ADDED       | constraint_type:FOREIGN KEY,column_name:owner_employee_id,definition:FOREIGN KEY (owner_employee_id) REFERENCES analytics_schema.employees(employee_id)
           2 | employees        | Reference      | fk_emp_dept          | b8d9ae77771da31847284c0e7d6d4462 | ADDED       | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
           2 | employees        | Reference      | fk_emp_manager       | 1d11e76a49d32520e6a69503c89d78c4 | ADDED       | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           2 | projects         | Reference      | fk_proj_owner        | e80df3f3baa79176a0352ea68ffc3db8 | ADDED       | source_column:owner_employee_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_proj_owner
           
           3 | employees        | Column         | dept_id              | 9c5093ee0f40611907ac98a547376575 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept_v2,ordinal_position:3
           3 | employees        | Column         | supervisor_id        | 8b3f013935a22769846f2b33a001c2c7 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_supervisor_v2,ordinal_position:4
           3 | employees        | Constraint     | fk_emp_dept_v2       | b00ca1ec8f6a40ea15ed663d463fd544 | ADDED       | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.departments(department_id)
           3 | employees        | Constraint     | fk_emp_supervisor_v2 | 527c29ac46598ad2d638ef6e9630ad45 | ADDED       | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id)
           3 | employees        | Reference      | fk_emp_dept_v2       | 6e57fb6937753202e2a05df3263afb57 | ADDED       | source_column:dept_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept_v2
           3 | employees        | Reference      | fk_emp_supervisor_v2 | 5979d7c355ec0b6fabba356fc4f9c97b | ADDED       | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_v2
           3 | employees        | Reference      | fk_emp_manager       | 1d11e76a49d32520e6a69503c89d78c4 | DELETED     | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           3 | employees        | Constraint     | fk_emp_dept          | d15c5860c9bccaa7101d3622732d6aa7 | DELETED     | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           3 | employees        | Column         | department_id        | 8c589519c4e1bcb99712c94a36eab2a5 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           3 | employees        | Column         | manager_id           | 44274eded9170b1215e53e763c8ef725 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           3 | employees        | Constraint     | fk_emp_manager       | 47616b219bed8eedf4c5d317305a56a6 | DELETED     | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           3 | employees        | Reference      | fk_emp_dept          | b8d9ae77771da31847284c0e7d6d4462 | DELETED     | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
(40 rows)
-- =============================================================
-- Test Run 3 — Referenced Table Rename + FK Recreation
-- =============================================================

-- Purpose: test behavior when referenced table is renamed.
ALTER TABLE analytics_schema.departments
    RENAME TO dept_master;
-- Must drop & recreate constraints
ALTER TABLE analytics_schema.employees DROP CONSTRAINT fk_emp_dept_v2;

ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_dept_v3
    FOREIGN KEY (dept_id)
    REFERENCES analytics_schema.dept_master(department_id);

    SELECT * FROM pdcd_schema.load_snapshot_tbl();
    SELECT * FROM pdcd_schema.compare_load_md5_metadata_tbl(ARRAY['analytics_schema']);
    TRUNCATE TABLE pdcd_schema.md5_metadata_staging_tbl RESTART IDENTITY CASCADE;
    SELECT * FROM pdcd_schema.load_md5_metadata_staging_tbl(ARRAY['analytics_schema']);
SELECT snapshot_id,object_type_name, object_subtype,    object_subtype_name, object_md5,    change_type, object_subtype_details from pdcd_schema.md5_metadata_tbl;
test_db=# SELECT snapshot_id,object_type_name, object_subtype,    object_subtype_name, object_md5,    change_type, object_subtype_details from pdcd_schema.md5_metadata_tbl;
 snapshot_id | object_type_name | object_subtype | object_subtype_name  |            object_md5            | change_type |                                                                                                                            object_subtype_details
-------------+------------------+----------------+----------------------+----------------------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
           1 | departments      | Column         | department_id        | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           1 | departments      | Column         | department_name      | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | employee_id          | 6b1b0723fc761b4f80b3ebd7347a2adc | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.employees_employee_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:employees_pkey,ordinal_position:1
           1 | employees        | Column         | employee_name        | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | department_id        | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | employees        | Column         | manager_id           | 23d773c000aa706b00d05e17a2b453dd | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4
           1 | locations        | Column         | location_id          | 7e303cc5a87a43fd7d157c8d405ead5b | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.locations_location_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:locations_pkey,ordinal_position:1
           1 | locations        | Column         | location_name        | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | project_id           | dd4a969c61f7438005de9cb441488853 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.projects_project_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:projects_pkey,ordinal_position:1
           1 | projects         | Column         | project_name         | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | owner_employee_id    | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | departments      | Constraint     | departments_pkey     | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           1 | employees        | Constraint     | employees_pkey       | 46e4d7c138cb7c7937bfd192b807b708 | ADDED       | constraint_type:PRIMARY KEY,column_name:employee_id,definition:PRIMARY KEY (employee_id)
           1 | locations        | Constraint     | locations_pkey       | fb2872ae6f850928fc245309c234f463 | ADDED       | constraint_type:PRIMARY KEY,column_name:location_id,definition:PRIMARY KEY (location_id)
           1 | projects         | Constraint     | projects_pkey        | 6f0219581bbe02a3a37894ac16b99524 | ADDED       | constraint_type:PRIMARY KEY,column_name:project_id,definition:PRIMARY KEY (project_id)
           1 | departments      | Index          | departments_pkey     | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           1 | employees        | Index          | employees_pkey       | 2ead719c29bb313dcd2fb7888d34134b | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX employees_pkey ON analytics_schema.employees USING btree (employee_id),is_unique:true,is_primary:true,index_columns:employee_id,index_predicate:,access_method:btree
           1 | locations        | Index          | locations_pkey       | c415021e5aaf76a347055504ddd89d2e | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX locations_pkey ON analytics_schema.locations USING btree (location_id),is_unique:true,is_primary:true,index_columns:location_id,index_predicate:,access_method:btree
           1 | projects         | Index          | projects_pkey        | dbf8303392b4b104fc49c2f1c98667e5 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX projects_pkey ON analytics_schema.projects USING btree (project_id),is_unique:true,is_primary:true,index_columns:project_id,index_predicate:,access_method:btree
           2 | employees        | Column         | department_id        | 8c589519c4e1bcb99712c94a36eab2a5 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           2 | employees        | Column         | manager_id           | 44274eded9170b1215e53e763c8ef725 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           2 | projects         | Column         | owner_employee_id    | 1e089843e40e8b5ad28d1193d17c7dca | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_proj_owner,ordinal_position:3
           2 | employees        | Constraint     | fk_emp_dept          | d15c5860c9bccaa7101d3622732d6aa7 | ADDED       | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           2 | employees        | Constraint     | fk_emp_manager       | 47616b219bed8eedf4c5d317305a56a6 | ADDED       | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           2 | projects         | Constraint     | fk_proj_owner        | 027aa00ae7569fb2d36ea6893728dc2d | ADDED       | constraint_type:FOREIGN KEY,column_name:owner_employee_id,definition:FOREIGN KEY (owner_employee_id) REFERENCES analytics_schema.employees(employee_id)
           2 | employees        | Reference      | fk_emp_dept          | b8d9ae77771da31847284c0e7d6d4462 | ADDED       | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
           2 | employees        | Reference      | fk_emp_manager       | 1d11e76a49d32520e6a69503c89d78c4 | ADDED       | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           2 | projects         | Reference      | fk_proj_owner        | e80df3f3baa79176a0352ea68ffc3db8 | ADDED       | source_column:owner_employee_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_proj_owner
           3 | employees        | Column         | dept_id              | 9c5093ee0f40611907ac98a547376575 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept_v2,ordinal_position:3
           3 | employees        | Column         | supervisor_id        | 8b3f013935a22769846f2b33a001c2c7 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_supervisor_v2,ordinal_position:4
           3 | employees        | Constraint     | fk_emp_dept_v2       | b00ca1ec8f6a40ea15ed663d463fd544 | ADDED       | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.departments(department_id)
           3 | employees        | Constraint     | fk_emp_supervisor_v2 | 527c29ac46598ad2d638ef6e9630ad45 | ADDED       | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id)
           3 | employees        | Reference      | fk_emp_dept_v2       | 6e57fb6937753202e2a05df3263afb57 | ADDED       | source_column:dept_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept_v2
           3 | employees        | Reference      | fk_emp_supervisor_v2 | 5979d7c355ec0b6fabba356fc4f9c97b | ADDED       | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_v2
           3 | employees        | Reference      | fk_emp_manager       | 1d11e76a49d32520e6a69503c89d78c4 | DELETED     | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           3 | employees        | Constraint     | fk_emp_dept          | d15c5860c9bccaa7101d3622732d6aa7 | DELETED     | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           3 | employees        | Column         | department_id        | 8c589519c4e1bcb99712c94a36eab2a5 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           3 | employees        | Column         | manager_id           | 44274eded9170b1215e53e763c8ef725 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           3 | employees        | Constraint     | fk_emp_manager       | 47616b219bed8eedf4c5d317305a56a6 | DELETED     | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           3 | employees        | Reference      | fk_emp_dept          | b8d9ae77771da31847284c0e7d6d4462 | DELETED     | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
           
           4 | employees        | Column         | dept_id              | 3dbe4bcc374a681df05459a798924e72 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept_v3,ordinal_position:3
           4 | dept_master      | Column         | department_id        | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           4 | dept_master      | Column         | department_name      | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           4 | dept_master      | Constraint     | departments_pkey     | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           4 | employees        | Constraint     | fk_emp_dept_v3       | 463b888b4428bf606a7fc892c6e46052 | ADDED       | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.dept_master(department_id)
           4 | dept_master      | Index          | departments_pkey     | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.dept_master USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           4 | employees        | Reference      | fk_emp_dept_v3       | 82ad33e2a777c6e4590cbae5103d7510 | ADDED       | source_column:dept_id,target_schema:analytics_schema,target_table:dept_master,target_column:department_id,constraint_name:fk_emp_dept_v3
           4 | departments      | Column         | department_name      | 3234b93fd696b402c777ba52943b52c2 | DELETED     | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           4 | departments      | Column         | department_id        | 57cdd3e718f6f0349c77a716434d09f8 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,
generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           4 | employees        | Constraint     | fk_emp_dept_v2       | b00ca1ec8f6a40ea15ed663d463fd544 | DELETED     | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.departments(department_id)
           4 | departments      | Constraint     | departments_pkey     | 6f00aac61324af405b95307a19340808 | DELETED     | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           4 | departments      | Index          | departments_pkey     | b42e577e3d023d664d051edb062f8b89 | DELETED     | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,a
ccess_method:btree
           4 | employees        | Reference      | fk_emp_dept_v2       | 6e57fb6937753202e2a05df3263afb57 | DELETED     | source_column:dept_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept_v2
(53 rows)
-- =============================================================
-- Test Run 4 — Cascading Behavior Updates
-- =============================================================
-- Purpose: track updates to ON DELETE / ON UPDATE rules
ALTER TABLE analytics_schema.employees DROP CONSTRAINT fk_emp_supervisor_v2;

ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_supervisor_cascade
    FOREIGN KEY (supervisor_id)
    REFERENCES analytics_schema.employees(employee_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

    SELECT * FROM pdcd_schema.load_snapshot_tbl();
    SELECT * FROM pdcd_schema.compare_load_md5_metadata_tbl(ARRAY['analytics_schema']);
    TRUNCATE TABLE pdcd_schema.md5_metadata_staging_tbl RESTART IDENTITY CASCADE;
    SELECT * FROM pdcd_schema.load_md5_metadata_staging_tbl(ARRAY['analytics_schema']);
SELECT snapshot_id,object_type_name, object_subtype,    object_subtype_name, object_md5,    change_type, object_subtype_details from pdcd_schema.md5_metadata_tbl;

 snapshot_id | object_type_name | object_subtype |    object_subtype_name    |            object_md5            | change_type |                                                                                                                            object_subtype_details
-------------+------------------+----------------+---------------------------+----------------------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
           1 | departments      | Column         | department_id             | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           1 | departments      | Column         | department_name           | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | employee_id               | 6b1b0723fc761b4f80b3ebd7347a2adc | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.employees_employee_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:employees_pkey,ordinal_position:1
           1 | employees        | Column         | employee_name             | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | department_id             | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | employees        | Column         | manager_id                | 23d773c000aa706b00d05e17a2b453dd | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4
           1 | locations        | Column         | location_id               | 7e303cc5a87a43fd7d157c8d405ead5b | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.locations_location_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:locations_pkey,ordinal_position:1
           1 | locations        | Column         | location_name             | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | project_id                | dd4a969c61f7438005de9cb441488853 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.projects_project_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:projects_pkey,ordinal_position:1
           1 | projects         | Column         | project_name              | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | owner_employee_id         | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | departments      | Constraint     | departments_pkey          | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           1 | employees        | Constraint     | employees_pkey            | 46e4d7c138cb7c7937bfd192b807b708 | ADDED       | constraint_type:PRIMARY KEY,column_name:employee_id,definition:PRIMARY KEY (employee_id)
           1 | locations        | Constraint     | locations_pkey            | fb2872ae6f850928fc245309c234f463 | ADDED       | constraint_type:PRIMARY KEY,column_name:location_id,definition:PRIMARY KEY (location_id)
           1 | projects         | Constraint     | projects_pkey             | 6f0219581bbe02a3a37894ac16b99524 | ADDED       | constraint_type:PRIMARY KEY,column_name:project_id,definition:PRIMARY KEY (project_id)
           1 | departments      | Index          | departments_pkey          | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           1 | employees        | Index          | employees_pkey            | 2ead719c29bb313dcd2fb7888d34134b | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX employees_pkey ON analytics_schema.employees USING btree (employee_id),is_unique:true,is_primary:true,index_columns:employee_id,index_predicate:,access_method:btree
           1 | locations        | Index          | locations_pkey            | c415021e5aaf76a347055504ddd89d2e | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX locations_pkey ON analytics_schema.locations USING btree (location_id),is_unique:true,is_primary:true,index_columns:location_id,index_predicate:,access_method:btree
           1 | projects         | Index          | projects_pkey             | dbf8303392b4b104fc49c2f1c98667e5 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX projects_pkey ON analytics_schema.projects USING btree (project_id),is_unique:true,is_primary:true,index_columns:project_id,index_predicate:,access_method:btree
           2 | employees        | Column         | department_id             | 8c589519c4e1bcb99712c94a36eab2a5 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           2 | employees        | Column         | manager_id                | 44274eded9170b1215e53e763c8ef725 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           2 | projects         | Column         | owner_employee_id         | 1e089843e40e8b5ad28d1193d17c7dca | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_proj_owner,ordinal_position:3
           2 | employees        | Constraint     | fk_emp_dept               | d15c5860c9bccaa7101d3622732d6aa7 | ADDED       | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           2 | employees        | Constraint     | fk_emp_manager            | 47616b219bed8eedf4c5d317305a56a6 | ADDED       | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           2 | projects         | Constraint     | fk_proj_owner             | 027aa00ae7569fb2d36ea6893728dc2d | ADDED       | constraint_type:FOREIGN KEY,column_name:owner_employee_id,definition:FOREIGN KEY (owner_employee_id) REFERENCES analytics_schema.employees(employee_id)
           2 | employees        | Reference      | fk_emp_dept               | b8d9ae77771da31847284c0e7d6d4462 | ADDED       | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
           2 | employees        | Reference      | fk_emp_manager            | 1d11e76a49d32520e6a69503c89d78c4 | ADDED       | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           2 | projects         | Reference      | fk_proj_owner             | e80df3f3baa79176a0352ea68ffc3db8 | ADDED       | source_column:owner_employee_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_proj_owner
           3 | employees        | Column         | dept_id                   | 9c5093ee0f40611907ac98a547376575 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept_v2,ordinal_position:3
           3 | employees        | Column         | supervisor_id             | 8b3f013935a22769846f2b33a001c2c7 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_supervisor_v2,ordinal_position:4
           3 | employees        | Constraint     | fk_emp_dept_v2            | b00ca1ec8f6a40ea15ed663d463fd544 | ADDED       | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.departments(department_id)
           3 | employees        | Constraint     | fk_emp_supervisor_v2      | 527c29ac46598ad2d638ef6e9630ad45 | ADDED       | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id)
           3 | employees        | Reference      | fk_emp_dept_v2            | 6e57fb6937753202e2a05df3263afb57 | ADDED       | source_column:dept_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept_v2
           3 | employees        | Reference      | fk_emp_supervisor_v2      | 5979d7c355ec0b6fabba356fc4f9c97b | ADDED       | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_v2
           3 | employees        | Reference      | fk_emp_manager            | 1d11e76a49d32520e6a69503c89d78c4 | DELETED     | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           3 | employees        | Constraint     | fk_emp_dept               | d15c5860c9bccaa7101d3622732d6aa7 | DELETED     | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           3 | employees        | Column         | department_id             | 8c589519c4e1bcb99712c94a36eab2a5 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           3 | employees        | Column         | manager_id                | 44274eded9170b1215e53e763c8ef725 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           3 | employees        | Constraint     | fk_emp_manager            | 47616b219bed8eedf4c5d317305a56a6 | DELETED     | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           3 | employees        | Reference      | fk_emp_dept               | b8d9ae77771da31847284c0e7d6d4462 | DELETED     | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
           4 | employees        | Column         | dept_id                   | 3dbe4bcc374a681df05459a798924e72 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept_v3,ordinal_position:3
           4 | dept_master      | Column         | department_id             | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           4 | dept_master      | Column         | department_name           | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           4 | dept_master      | Constraint     | departments_pkey          | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           4 | employees        | Constraint     | fk_emp_dept_v3            | 463b888b4428bf606a7fc892c6e46052 | ADDED       | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.dept_master(department_id)
           4 | dept_master      | Index          | departments_pkey          | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.dept_master USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           4 | employees        | Reference      | fk_emp_dept_v3            | 82ad33e2a777c6e4590cbae5103d7510 | ADDED       | source_column:dept_id,target_schema:analytics_schema,target_table:dept_master,target_column:department_id,constraint_name:fk_emp_dept_v3
           4 | departments      | Column         | department_name           | 3234b93fd696b402c777ba52943b52c2 | DELETED     | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           4 | departments      | Column         | department_id             | 57cdd3e718f6f0349c77a716434d09f8 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           4 | employees        | Constraint     | fk_emp_dept_v2            | b00ca1ec8f6a40ea15ed663d463fd544 | DELETED     | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.departments(department_id)
           4 | departments      | Constraint     | departments_pkey          | 6f00aac61324af405b95307a19340808 | DELETED     | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           4 | departments      | Index          | departments_pkey          | b42e577e3d023d664d051edb062f8b89 | DELETED     | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           4 | employees        | Reference      | fk_emp_dept_v2            | 6e57fb6937753202e2a05df3263afb57 | DELETED     | source_column:dept_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept_v2
           
           5 | employees        | Column         | supervisor_id             | c72dc60780af729f75143a4f1679d407 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_supervisor_cascade,ordinal_position:4
           5 | employees        | Constraint     | fk_emp_supervisor_cascade | 810ba0498113080b34f76b3d922b75f6 | ADDED       | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL
           5 | employees        | Reference      | fk_emp_supervisor_cascade | eef93a239a49f538157ea5549bdd2458 | ADDED       | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_cascade
           5 | employees        | Constraint     | fk_emp_supervisor_v2      | 527c29ac46598ad2d638ef6e9630ad45 | DELETED     | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id)
           5 | employees        | Reference      | fk_emp_supervisor_v2      | 5979d7c355ec0b6fabba356fc4f9c97b | DELETED     | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_v2
(58 rows)

ALTER TABLE analytics_schema.employees DROP CONSTRAINT fk_emp_supervisor_v2;

ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_supervisor_cascade
    FOREIGN KEY (supervisor_id)
    REFERENCES analytics_schema.employees(employee_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

-- =============================================================
-- Test Run 5 — Complex FK Restructuring
-- =============================================================

-- Purpose: simulate heavy refactoring of relationships.
-- Drop FKs
ALTER TABLE analytics_schema.employees DROP CONSTRAINT fk_emp_dept_v3;
ALTER TABLE analytics_schema.employees DROP CONSTRAINT fk_emp_supervisor_cascade;
ALTER TABLE analytics_schema.projects DROP CONSTRAINT fk_proj_owner;

-- Add new FKs with multiple column remaps
ALTER TABLE analytics_schema.employees
    ADD COLUMN location_id INT;

ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_location
    FOREIGN KEY (location_id)
    REFERENCES analytics_schema.locations(location_id);

ALTER TABLE analytics_schema.projects
    ADD CONSTRAINT fk_proj_owner_v2
    FOREIGN KEY (owner_employee_id)
    REFERENCES analytics_schema.employees(employee_id)
    ON DELETE CASCADE;

    SELECT * FROM pdcd_schema.load_snapshot_tbl();
    SELECT * FROM pdcd_schema.compare_load_md5_metadata_tbl(ARRAY['analytics_schema']);
    TRUNCATE TABLE pdcd_schema.md5_metadata_staging_tbl RESTART IDENTITY CASCADE;
    SELECT * FROM pdcd_schema.load_md5_metadata_staging_tbl(ARRAY['analytics_schema']);
SELECT snapshot_id,object_type_name, object_subtype,    object_subtype_name, object_md5,    change_type, object_subtype_details from pdcd_schema.md5_metadata_tbl;
 snapshot_id | object_type_name | object_subtype |    object_subtype_name    |            object_md5            | change_type |                                                                                                                            object_subtype_details
-------------+------------------+----------------+---------------------------+----------------------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
           1 | departments      | Column         | department_id             | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           1 | departments      | Column         | department_name           | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | employee_id               | 6b1b0723fc761b4f80b3ebd7347a2adc | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.employees_employee_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:employees_pkey,ordinal_position:1
           1 | employees        | Column         | employee_name             | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | employees        | Column         | department_id             | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | employees        | Column         | manager_id                | 23d773c000aa706b00d05e17a2b453dd | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4
           1 | locations        | Column         | location_id               | 7e303cc5a87a43fd7d157c8d405ead5b | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.locations_location_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:locations_pkey,ordinal_position:1
           1 | locations        | Column         | location_name             | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | project_id                | dd4a969c61f7438005de9cb441488853 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.projects_project_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:projects_pkey,ordinal_position:1
           1 | projects         | Column         | project_name              | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           1 | projects         | Column         | owner_employee_id         | 1850f45d852a80af76263018af147dd8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           1 | departments      | Constraint     | departments_pkey          | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           1 | employees        | Constraint     | employees_pkey            | 46e4d7c138cb7c7937bfd192b807b708 | ADDED       | constraint_type:PRIMARY KEY,column_name:employee_id,definition:PRIMARY KEY (employee_id)
           1 | locations        | Constraint     | locations_pkey            | fb2872ae6f850928fc245309c234f463 | ADDED       | constraint_type:PRIMARY KEY,column_name:location_id,definition:PRIMARY KEY (location_id)
           1 | projects         | Constraint     | projects_pkey             | 6f0219581bbe02a3a37894ac16b99524 | ADDED       | constraint_type:PRIMARY KEY,column_name:project_id,definition:PRIMARY KEY (project_id)
           1 | departments      | Index          | departments_pkey          | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           1 | employees        | Index          | employees_pkey            | 2ead719c29bb313dcd2fb7888d34134b | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX employees_pkey ON analytics_schema.employees USING btree (employee_id),is_unique:true,is_primary:true,index_columns:employee_id,index_predicate:,access_method:btree
           1 | locations        | Index          | locations_pkey            | c415021e5aaf76a347055504ddd89d2e | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX locations_pkey ON analytics_schema.locations USING btree (location_id),is_unique:true,is_primary:true,index_columns:location_id,index_predicate:,access_method:btree
           1 | projects         | Index          | projects_pkey             | dbf8303392b4b104fc49c2f1c98667e5 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX projects_pkey ON analytics_schema.projects USING btree (project_id),is_unique:true,is_primary:true,index_columns:project_id,index_predicate:,access_method:btree
           2 | employees        | Column         | department_id             | 8c589519c4e1bcb99712c94a36eab2a5 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           2 | employees        | Column         | manager_id                | 44274eded9170b1215e53e763c8ef725 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           2 | projects         | Column         | owner_employee_id         | 1e089843e40e8b5ad28d1193d17c7dca | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_proj_owner,ordinal_position:3
           2 | employees        | Constraint     | fk_emp_dept               | d15c5860c9bccaa7101d3622732d6aa7 | ADDED       | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           2 | employees        | Constraint     | fk_emp_manager            | 47616b219bed8eedf4c5d317305a56a6 | ADDED       | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           2 | projects         | Constraint     | fk_proj_owner             | 027aa00ae7569fb2d36ea6893728dc2d | ADDED       | constraint_type:FOREIGN KEY,column_name:owner_employee_id,definition:FOREIGN KEY (owner_employee_id) REFERENCES analytics_schema.employees(employee_id)
           2 | employees        | Reference      | fk_emp_dept               | b8d9ae77771da31847284c0e7d6d4462 | ADDED       | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
           2 | employees        | Reference      | fk_emp_manager            | 1d11e76a49d32520e6a69503c89d78c4 | ADDED       | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           2 | projects         | Reference      | fk_proj_owner             | e80df3f3baa79176a0352ea68ffc3db8 | ADDED       | source_column:owner_employee_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_proj_owner
           3 | employees        | Column         | dept_id                   | 9c5093ee0f40611907ac98a547376575 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept_v2,ordinal_position:3
           3 | employees        | Column         | supervisor_id             | 8b3f013935a22769846f2b33a001c2c7 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_supervisor_v2,ordinal_position:4
           3 | employees        | Constraint     | fk_emp_dept_v2            | b00ca1ec8f6a40ea15ed663d463fd544 | ADDED       | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.departments(department_id)
           3 | employees        | Constraint     | fk_emp_supervisor_v2      | 527c29ac46598ad2d638ef6e9630ad45 | ADDED       | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id)
           3 | employees        | Reference      | fk_emp_dept_v2            | 6e57fb6937753202e2a05df3263afb57 | ADDED       | source_column:dept_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept_v2
           3 | employees        | Reference      | fk_emp_supervisor_v2      | 5979d7c355ec0b6fabba356fc4f9c97b | ADDED       | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_v2
           3 | employees        | Reference      | fk_emp_manager            | 1d11e76a49d32520e6a69503c89d78c4 | DELETED     | source_column:manager_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_manager
           3 | employees        | Constraint     | fk_emp_dept               | d15c5860c9bccaa7101d3622732d6aa7 | DELETED     | constraint_type:FOREIGN KEY,column_name:department_id,definition:FOREIGN KEY (department_id) REFERENCES analytics_schema.departments(department_id)
           3 | employees        | Column         | department_id             | 8c589519c4e1bcb99712c94a36eab2a5 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept,ordinal_position:3
           3 | employees        | Column         | manager_id                | 44274eded9170b1215e53e763c8ef725 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_manager,ordinal_position:4
           3 | employees        | Constraint     | fk_emp_manager            | 47616b219bed8eedf4c5d317305a56a6 | DELETED     | constraint_type:FOREIGN KEY,column_name:manager_id,definition:FOREIGN KEY (manager_id) REFERENCES analytics_schema.employees(employee_id)
           3 | employees        | Reference      | fk_emp_dept               | b8d9ae77771da31847284c0e7d6d4462 | DELETED     | source_column:department_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept
           4 | employees        | Column         | dept_id                   | 3dbe4bcc374a681df05459a798924e72 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_dept_v3,ordinal_position:3
           4 | dept_master      | Column         | department_id             | 57cdd3e718f6f0349c77a716434d09f8 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           4 | dept_master      | Column         | department_name           | 3234b93fd696b402c777ba52943b52c2 | ADDED       | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           4 | dept_master      | Constraint     | departments_pkey          | 6f00aac61324af405b95307a19340808 | ADDED       | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           4 | employees        | Constraint     | fk_emp_dept_v3            | 463b888b4428bf606a7fc892c6e46052 | ADDED       | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.dept_master(department_id)
           4 | dept_master      | Index          | departments_pkey          | b42e577e3d023d664d051edb062f8b89 | ADDED       | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.dept_master USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           4 | employees        | Reference      | fk_emp_dept_v3            | 82ad33e2a777c6e4590cbae5103d7510 | ADDED       | source_column:dept_id,target_schema:analytics_schema,target_table:dept_master,target_column:department_id,constraint_name:fk_emp_dept_v3
           4 | departments      | Column         | department_name           | 3234b93fd696b402c777ba52943b52c2 | DELETED     | data_type:text,max_length:,numeric_precision:,numeric_scale:,nullable:NO,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:2
           4 | departments      | Column         | department_id             | 57cdd3e718f6f0349c77a716434d09f8 | DELETED     | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:NO,default_value:nextval('analytics_schema.departments_department_id_seq'::regclass),is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:departments_pkey,ordinal_position:1
           4 | employees        | Constraint     | fk_emp_dept_v2            | b00ca1ec8f6a40ea15ed663d463fd544 | DELETED     | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.departments(department_id)
           4 | departments      | Constraint     | departments_pkey          | 6f00aac61324af405b95307a19340808 | DELETED     | constraint_type:PRIMARY KEY,column_name:department_id,definition:PRIMARY KEY (department_id)
           4 | departments      | Index          | departments_pkey          | b42e577e3d023d664d051edb062f8b89 | DELETED     | tablespace:,indexdef:CREATE UNIQUE INDEX departments_pkey ON analytics_schema.departments USING btree (department_id),is_unique:true,is_primary:true,index_columns:department_id,index_predicate:,access_method:btree
           4 | employees        | Reference      | fk_emp_dept_v2            | 6e57fb6937753202e2a05df3263afb57 | DELETED     | source_column:dept_id,target_schema:analytics_schema,target_table:departments,target_column:department_id,constraint_name:fk_emp_dept_v2
           5 | employees        | Column         | supervisor_id             | c72dc60780af729f75143a4f1679d407 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_supervisor_cascade,ordinal_position:4
           5 | employees        | Constraint     | fk_emp_supervisor_cascade | 810ba0498113080b34f76b3d922b75f6 | ADDED       | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL
           5 | employees        | Reference      | fk_emp_supervisor_cascade | eef93a239a49f538157ea5549bdd2458 | ADDED       | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_cascade
           5 | employees        | Constraint     | fk_emp_supervisor_v2      | 527c29ac46598ad2d638ef6e9630ad45 | DELETED     | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id)
           5 | employees        | Reference      | fk_emp_supervisor_v2      | 5979d7c355ec0b6fabba356fc4f9c97b | DELETED     | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_v2
           
           6 | employees        | Column         | dept_id                   | 1850f45d852a80af76263018af147dd8 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:3
           6 | employees        | Column         | supervisor_id             | 23d773c000aa706b00d05e17a2b453dd | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:,ordinal_position:4
           6 | projects         | Column         | owner_employee_id         | a5ada486df17049f34256789370b0761 | MODIFIED    | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_proj_owner_v2,ordinal_position:3
           6 | employees        | Column         | location_id               | c9d7014d1de9186339ebc2c46ee0fb44 | ADDED       | data_type:integer,max_length:,numeric_precision:32,numeric_scale:0,nullable:YES,default_value:,is_identity:NO,is_generated:NEVER,generation_expression:,constraint_name:fk_emp_location,ordinal_position:5
           6 | employees        | Constraint     | fk_emp_location           | 664f94df8dcea2e7348330799eceb555 | ADDED       | constraint_type:FOREIGN KEY,column_name:location_id,definition:FOREIGN KEY (location_id) REFERENCES analytics_schema.locations(location_id)
           6 | projects         | Constraint     | fk_proj_owner_v2          | d52f4c19d0841c84370f824673a27597 | ADDED       | constraint_type:FOREIGN KEY,column_name:owner_employee_id,definition:FOREIGN KEY (owner_employee_id) REFERENCES analytics_schema.employees(employee_id) ON DELETE CASCADE
           6 | employees        | Reference      | fk_emp_location           | 7beaed3925617d55dafcb6e14c171d30 | ADDED       | source_column:location_id,target_schema:analytics_schema,target_table:locations,target_column:location_id,constraint_name:fk_emp_location
           6 | projects         | Reference      | fk_proj_owner_v2          | c61dd44f2e09c9d6ea84323df7407c22 | ADDED       | source_column:owner_employee_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_proj_owner_v2
           6 | employees        | Constraint     | fk_emp_dept_v3            | 463b888b4428bf606a7fc892c6e46052 | DELETED     | constraint_type:FOREIGN KEY,column_name:dept_id,definition:FOREIGN KEY (dept_id) REFERENCES analytics_schema.dept_master(department_id)
           6 | employees        | Constraint     | fk_emp_supervisor_cascade | 810ba0498113080b34f76b3d922b75f6 | DELETED     | constraint_type:FOREIGN KEY,column_name:supervisor_id,definition:FOREIGN KEY (supervisor_id) REFERENCES analytics_schema.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL
           6 | projects         | Constraint     | fk_proj_owner             | 027aa00ae7569fb2d36ea6893728dc2d | DELETED     | constraint_type:FOREIGN KEY,column_name:owner_employee_id,definition:FOREIGN KEY (owner_employee_id) REFERENCES analytics_schema.employees(employee_id)
           6 | projects         | Reference      | fk_proj_owner             | e80df3f3baa79176a0352ea68ffc3db8 | DELETED     | source_column:owner_employee_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_proj_owner
           6 | employees        | Reference      | fk_emp_supervisor_cascade | eef93a239a49f538157ea5549bdd2458 | DELETED     | source_column:supervisor_id,target_schema:analytics_schema,target_table:employees,target_column:employee_id,constraint_name:fk_emp_supervisor_cascade
           6 | employees        | Reference      | fk_emp_dept_v3            | 82ad33e2a777c6e4590cbae5103d7510 | DELETED     | source_column:dept_id,target_schema:analytics_schema,target_table:dept_master,target_column:department_id,constraint_name:fk_emp_dept_v3
(72 rows)

ALTER TABLE analytics_schema.employees
    ADD COLUMN location_id INT;

ALTER TABLE analytics_schema.employees
    ADD CONSTRAINT fk_emp_location
    FOREIGN KEY (location_id)
    REFERENCES analytics_schema.locations(location_id);

ALTER TABLE analytics_schema.projects
    ADD CONSTRAINT fk_proj_owner_v2
    FOREIGN KEY (owner_employee_id)
    REFERENCES analytics_schema.employees(employee_id)
    ON DELETE CASCADE;